name: Go CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go (match project: 1.25)
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Go version
        run: go version

      - name: Lint (golangci-lint latest, supports Go 1.25)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -v
